name = "BayesBase"
uuid = "b4ee3484-f114-42fe-b91c-797d54a0c67e"
authors = ["Bagaev Dmitry <bvdmitri@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
